C_INCLUDES =  \
-IDrivers/STM32F2xx_HAL_Driver/Inc \
-IDrivers/STM32F2xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/DFU/Inc \
-IDrivers/CMSIS/Device/ST/STM32F2xx/Include \
-IDrivers/CMSIS/Include \
-IUSB_DEVICE/App \
-IUSB_DEVICE/Target \
-ICore/Inc \
-Iaes/Inc \
-Icommon/Inc \
-IUnity